;funcion principal que toma los datos básicos para ejecutar el programa
(define tamañom 0)
(define tamañoc 0)
(define precio 0)
(define tipo 0)
(define placa 0)
(define hora 0)
(define vehiculo 0)
(define pos 0)
(define retirar 0)
(define (principal opcion motos carros horam horac)
  (display "Hola! estos son los datos que necesito para el parqueadero:")
  (newline)
  (display "ingrese el numero de espacios de parqueo para motos:")
  (set! tamañom (read))
  (newline)
  (display "ingrese el numero de espacios de parqueo para carros:")
  (set! tamañoc (read))
  (newline)
  (display "ingrese el precio por hora:")
  (set! precio (read))
  (define motos (make-vector tamañom 0))
  (define carros (make-vector tamañoc 0))
  (define horam (make-vector tamañom 0))
  (define horac (make-vector tamañoc 0))
  (menu opcion motos carros horam horac)
  )

;funcion menu que muestra las opciones a ejecutar
(define (menu opcion motos carros horam horac)
  (display "\n\nBIENVENIDO")
  (newline)
  (display "1. parquear un vehiculo")
  (newline)
  (display "2. retirar un vehiculo")
  (newline)
  (display "3. consultar espacios ocupados y desocupados")
  (newline)
  (display "4. salir")
  (newline)
  (display "escriba la opción que desea ejecutar:")
  (set! opcion (read))
  (seleccion opcion motos carros horam horac)
  )

;funcion que ejecuta las opciones seleccionadas
 (define (seleccion opcion motos carros horam horac)
   (cond
     ((= opcion 1)
      (display "ingrese el tipo de vehiculo (escriba 1 si es moto o 2 si es carro):")
      (set! tipo (read))
      (display "ingrese la placa del vehiculo (solo numeros):")
      (set! placa (read))
      (display motos)
      (newline)
      (set! pos (read))
      (insertar_placa carros pos placa)
      (if (= tipo 1)
          (insertar_placa motos pos placa)
          (insertar_placa carros pos placa)
      )
      (display "ingrese la hora de entrada del vehiculo:")
      (set! hora (read))
      (display hora)
      (if (= tipo 1)
          (insertar_hora horam 0 0)
          (insertar_hora horac 0 0)
      )
      (menu opcion motos carros horam horac)
     )
     ((= opcion 2)(display "ingrese el tipo de vehiculo que desea retirar (escriba 1 si es moto o 2 si es carro):")
                (set! vehiculo (read))
                (if (= vehiculo 1)
                    (begin
                      (display "ingrese la placa del vehiculo que desea retirar:")
                      (set! retirar (read))
                      (set! pos (buscar motos retirar 0))
                      (display pos)
                      (if (equal? pos -1)
                          (display "no esta")
                          (begin
                            (vector-set! motos pos 0)
                            (display motos)
                            )
                          )             )
                    )
                (menu opcion motos carros horam horac)
                )
   ((= opcion 4) (display "Adios, Vuelve pronto!! Gracias por usar nuestros servicios!!"))
   ((= opcion 5) (display "\n\n") (display motos) (display "\n\n") (menu opcion motos carros horam horac))
   )
)
                
;funcion que inserta placa del vehiculo en el vector correspondiente
(define (insertar_placa v pos placa)
  (vector-set! v pos placa)
  )

;funcion que inserta la hora de entrada del vehiculo en el vector correspondiente
(define (insertar_hora v pos hora)
  (vector-set! v pos hora)
  )

;funcion que busca un elemento en un vector
(define (buscar v elemento pos)
  (if (< pos (vector-length v))
      (begin
        (if (= elemento (vector-ref v pos))
            pos
            (buscar v elemento (+ pos 1))
        )  
      )
      -1
  )
)

;funcion que cuenta los espacios desocupados en el vector correspondiente
(define (espaciosd v pos)
  (if (= 0 (vector-ref v pos))
      1
      (+ (espaciosd v (+ pos 1)))
      )
  )

;funcion que cuenta los espacios ocupados en el vector correspondiente
(define (espacioso v pos)
  (if (not (= 0 (vector-ref v pos)))
      1
      (+ (espacioso v (+ pos 1)))
      )
  )

;Ejecucion del Proyecto
(principal 0 0 0 0 0)           